In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9423, 7083, 6743, 574],
 [9423, 7083, 6743, 7300],
 [9423, 5435, 6743, 5419],
 [5908, 4485, 9494, 1572, 8379],
 [5908, 4485, 9494, 1572, 828],
 [2838, 9423, 4188, 6743, 6204],
 [8934, 8472, 9092, 1572]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9423 7083 6743  574]
 [   0    0    0    0 9423 7083 6743 7300]
 [   0    0    0    0 9423 5435 6743 5419]
 [   0    0    0 5908 4485 9494 1572 8379]
 [   0    0    0 5908 4485 9494 1572  828]
 [   0    0    0 2838 9423 4188 6743 6204]
 [   0    0    0    0 8934 8472 9092 1572]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 166ms/step


array([[[-1.16665475e-02,  4.05351631e-02,  2.19088085e-02,
         -3.36164832e-02, -1.41560324e-02,  9.85467434e-03,
         -4.88790050e-02, -4.31258194e-02,  2.28983872e-02,
         -4.88369577e-02],
        [-1.16665475e-02,  4.05351631e-02,  2.19088085e-02,
         -3.36164832e-02, -1.41560324e-02,  9.85467434e-03,
         -4.88790050e-02, -4.31258194e-02,  2.28983872e-02,
         -4.88369577e-02],
        [-1.16665475e-02,  4.05351631e-02,  2.19088085e-02,
         -3.36164832e-02, -1.41560324e-02,  9.85467434e-03,
         -4.88790050e-02, -4.31258194e-02,  2.28983872e-02,
         -4.88369577e-02],
        [-1.16665475e-02,  4.05351631e-02,  2.19088085e-02,
         -3.36164832e-02, -1.41560324e-02,  9.85467434e-03,
         -4.88790050e-02, -4.31258194e-02,  2.28983872e-02,
         -4.88369577e-02],
        [ 8.07406753e-03, -2.09822189e-02, -1.14070177e-02,
          1.47717930e-02, -4.62814830e-02,  3.91521193e-02,
         -2.89703738e-02, -1.84370875e-02, -4.536038

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 9423, 7083, 6743,  574])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 60ms/step


array([[-0.01166655,  0.04053516,  0.02190881, -0.03361648, -0.01415603,
         0.00985467, -0.04887901, -0.04312582,  0.02289839, -0.04883696],
       [-0.01166655,  0.04053516,  0.02190881, -0.03361648, -0.01415603,
         0.00985467, -0.04887901, -0.04312582,  0.02289839, -0.04883696],
       [-0.01166655,  0.04053516,  0.02190881, -0.03361648, -0.01415603,
         0.00985467, -0.04887901, -0.04312582,  0.02289839, -0.04883696],
       [-0.01166655,  0.04053516,  0.02190881, -0.03361648, -0.01415603,
         0.00985467, -0.04887901, -0.04312582,  0.02289839, -0.04883696],
       [ 0.00807407, -0.02098222, -0.01140702,  0.01477179, -0.04628148,
         0.03915212, -0.02897037, -0.01843709, -0.04536039,  0.03117924],
       [ 0.00692851, -0.04261503, -0.02506053,  0.0126476 ,  0.04018501,
        -0.02485023, -0.04826254, -0.00343281, -0.01763212,  0.0118883 ],
       [ 0.02727458, -0.02593842, -0.02413434, -0.00358362,  0.03245293,
        -0.03367047, -0.00614069,  0.0020679 